# ─────────────────────────────────────────────────────
# src/main/resources/application.yml
# ─────────────────────────────────────────────────────

# ── alias para KafkaConfig antigo ───────────────────
kafka:
  bootstrap-servers: ${spring.kafka.bootstrap-servers}

spring:
  application:
    name: order-processing-service

  datasource:
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/fake/.well-known/jwks.json

  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: false
    consumer:
      group-id: invoice-service
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
      retry:
        max-attempts: 3
        backoff:
          initial-interval: 5000
          multiplier: 2
          max-interval: 30000

aws:
  region: us-east-1
  s3:
    bucket-name: order-processing-service-invoices

management:
  health:
    kafka:
      enabled: false
